<?php

namespace AppBundle\Repository;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends \Doctrine\ORM\EntityRepository
{
    public function findGender()
    {
        return $this
            ->createQueryBuilder('author')
            //->where('author.gender = :sex')
            //->setParameter('sex', 1)
            ->getQuery()// сворачивает все что написали в запрос
            ->getResult(); // возвращает массив из сущности которую найдет
    }

}



